defaults: &defaults
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  username: <%= Settings.database.username %>
  password: "<%= Settings.database.password %>"
  pool: 12

development:
  <<: *defaults
  database: minsheng_development

production:
  <<: *defaults
  database: minsheng_production

test: &test
  <<: *defaults
  database: minsheng_test
