class Category < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :name, :parent, :parent_id

  # relationships .............................................................
  has_many :shops

  has_many :category_tags, dependent: :destroy
  has_many :tags, through: :category_tags


  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................

  # additional config .........................................................
  has_ancestry

  # class methods .............................................................

  # public instance methods ...................................................
  def insert(parent_id)
    if parent_id and parent_id != ""
      # logger.info("-----------------")
      # logger.info(parent_id)
      Category.find(parent_id).children.create :name => self.name
    else
      Category.create! :name => self.name
    end
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
