# -*- encoding: utf-8 -*-
class City < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :name, :province_id, :level, :zip_code, :pinyin, :pinyin_abbr

  # relationships .............................................................
  belongs_to :province
  has_many :districts, dependent: :destroy

  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................

  # public instance methods ...................................................
  def short_name
    @short_name ||= name.gsub(/市|自治州|地区|特别行政区/,'')
  end

  def brothers
    @brothers ||= City.where("province_id = #{province_id}")
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
