# -*- encoding: utf-8 -*-
class District < ActiveRecord::Base
	# extends ...................................................................
  # includes ..................................................................

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :name, :city_id, :pinyin, :pinyin_abbr

  # relationships .............................................................
	belongs_to :city
	belongs_to :province
  has_many :communities
  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................

  # public instance methods ...................................................
  def short_name
		@short_name ||= name.gsub(/区|县|市|自治县/,'')
	end

	def brothers
		@brothers ||= District.where("city_id = #{city_id}")
	end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
