# encoding: utf-8

class Notice < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :content, :flag_type, :title, :start_time, :end_time

  # relationships .............................................................

  # constants definition ......................................................
  FLAG_TYPE = { '前' => 1, '后' => 2, '左' => 3, '右' => 4 }

  # validations ...............................................................
  validates :content, :flag_type, :title, :start_time, :end_time, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................

  # public instance methods ...................................................
  def flag_text
    flag_type.nil? ? nil : FLAG_TYPE.key(flag_type.to_i)
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
