class Rate < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :comment, :rank

  # relationships .............................................................
  belongs_to :user
  belongs_to :shop

  # constants definition ......................................................

  # validations ...............................................................
    # validates :rank, presence: true
    # validates :rank, {:greater_than 0, :less_than 6}
    # validates :comment, length: { minimum: 2, maximum: 500 }

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
