class ShopImage < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................

  # security (i.e. attr_accessible) ...........................................

  # relationships .............................................................
  attr_accessible :shop_id, :image, :name, :flag_type

  
  belongs_to :shop

  # constants definition ......................................................
  # validations ...............................................................
  validates :image, presence: true
  # callbacks .................................................................
  # scopes ....................................................................

  # additional config .........................................................
  mount_uploader :image, ShopImageUploader

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  def save
    logger.info("====save====") 
  end
end
