class Tag < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  attr_accessible :name

  # relationships .............................................................
  has_many :taggings
  has_many :shops, through: :taggings

  has_many :category_tags, dependent: :destroy
  has_many :categories, through: :category_tags

  # constants definition ......................................................

  # validations ...............................................................
  validates :name, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
